version: '2.1'
services:
  nginx:
    depends_on: 
      - api
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
      - external
  api:
    depends_on:
      - mysql
    build: ./src/GlueHome.Api
    environment:
      MYSQL_CONNECTION_STRING: host=mysql;port=3306;user id=api;password=api;database=logistics;
    networks:
      - internal
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./etc/mysql:/etc/mysql
      - ./volumes/mysql:/var/lib/mysql
      - ./scripts/mysql/init:/docker-entrypoint-initdb.d/:ro
    command: [mysqld, --bind-address=0.0.0.0]
    networks:
      - internal
networks:
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
  internal:
    driver: bridge
    internal: true
