version: '2.1'
services:
  nginx:
    depends_on: 
      - api
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - internal
      - external
  api:
    depends_on:
      - mysql
    build: ./src/GlueHome.Api
    environment:
      MYSQL_CONNECTION_STRING: host=mysql;port=3306;user id=api;password=api;database=logistics;
    networks:
      - internal
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./etc/mysql:/etc/mysql
      - ./volumes/mysql:/var/lib/mysql
      - ./scripts/mysql/init:/docker-entrypoint-initdb.d/:ro
    command: [mysqld, --bind-address=0.0.0.0]
    networks:
      - internal
  elasticsearch:
    image: elasticsearch:7.5.1
    ports:
      - 9200:9200
    environment:
      - cluster.name=gluehome-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
      - ./volumes/elasticsearch/lib:/var/lib/elasticsearch
    networks:
      - internal
  grafana:
    depends_on: 
      - prometheus
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./volumes/grafana:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_USER: grafana
      GF_SECURITY_ADMIN_PASSWORD: grafana
      GF_USERS_ALLOW_SIGN_UP: "false"
    links:
      - prometheus
    networks:
      - internal
      - external
  prometheus:
    depends_on: 
      - api
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./volumes/prometheus:/prometheus
    networks:
      - internal
    command:
      - --config.file=/etc/prometheus/prometheus.yml
networks:
  external:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
  internal:
    driver: bridge
    internal: true
