global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    metrics_path: '/mgmt/prometheus'
    static_configs:
      - targets:
        - api:5001
